name:                multisock
version:             0.1.0.0
github:              "konn/multisock"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro_at_gmail.com"
copyright:           "2024 (c) Hiromi ISHII"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/konn/multisock#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - fsnotify
  - generic-lens
  - githash
  - optparse-applicative
  - path
  - path-io
  - rio
  - streaming-bytestring
  - streaming-commons
  - template-haskell
  - yaml

executables:
  multisock:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - '"-with-rtsopts=-N --nonmoving-gc"'
    dependencies:
    - multisock

tests:
  multisock-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multisock
